version: "3"

services:
  
  php:
    container_name: "rat_php"
    restart: always
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - dev

  nginx:
    container_name: "rat_nginx"
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "81:80"
    networks:
      - dev
    links:
      - php
  mongodb:
    image : mongo:latest
    container_name: api_db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db-data:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:
volumes:
  db-data:
