version: "3"

services:
  
  php:
    container_name: "rat_php"
    restart: always
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - dev

  nginx:
    container_name: "rat_nginx"
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "81:80"
    networks:
      - dev
    links:
      - php
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ratdb
      MONGO_INITDB_ROOT_USERNAME: rat
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/data/db


networks:
  dev:
volumes:
  db-data:
